version: 2
jobs:
  build:
    parallelism: 3
    working_directory: /Users/david/SoftwareDevelopment/MakeItReal/Projects/Rails_2/mis_gastos/test
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: mis_gastos
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: mis_gastos
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""
          workflows:
  steps:
    - checkout
    - type: cache-restore
      name: Restore bundle cache
      key: mis_gastos-bundle-{{ checksum "Gemfile.lock" }}

   - run:
     name: Bundle Install
     command: bundle install --path vendor/bundle

  - type: cache-save
    name: Store bundle cache
    key: mis_gastos-bundle-{{ checksum "Gemfile.lock" }}
    paths:
      - vendor/bundle
      - type: cache-restore
    name: Restore yarn cache
    key: rails-demo-yarn-{{ checksum "yarn.lock" }}

  - run:
      name: Yarn Install
      command: yarn install

  # Store yarn / webpacker cache
  - type: cache-save
    name: Store yarn cache
    key: rails-demo-yarn-{{ checksum "yarn.lock" }}
    paths:
      - ~/.yarn-cache
   - run:
      name: Wait for DB
      command: dockerize -wait tcp://localhost:3000 -timeout 1m

  - run:
      name: Database setup
      command: bin/rails db:schema:load --trace
