version: 2
jobs:
   build:
     docker:
       - image: circleci/Ruby:<2.4>
     steps:
       - checkout
         - run:
             name: Greeting
             command: echo Hello, world.
         - run:
             name: Print the Current Time
             command: date
